# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='art',
            field=models.ImageField(default='static/uploads/no-pic.jpg', upload_to='static/uploads'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_length',
            field=models.CharField(choices=[('2', '2 Weeks'), ('8', '8 Weeks')], default='2', max_length=30),
        ),
    ]
