# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160226_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='art',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
